package iuh.fit.goat.config;

import iuh.fit.goat.common.Gender;
import iuh.fit.goat.entity.*;
import iuh.fit.goat.entity.embeddable.Contact;
import iuh.fit.goat.repository.*;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Service
public class DatabaseInitializer implements CommandLineRunner {
    private final RoleRepository roleRepository;
    private final PermissionRepository permissionRepository;
    private final UserRepository userRepository;
    private final SkillRepository skillRepository;
    private final CareerRepository careerRepository;
    private final PasswordEncoder passwordEncoder;

    public DatabaseInitializer(RoleRepository roleRepository, PermissionRepository permissionRepository,
                               UserRepository userRepository, PasswordEncoder passwordEncoder,
                               CareerRepository careerRepository, SkillRepository skillRepository
    ) {
        this.roleRepository = roleRepository;
        this.permissionRepository = permissionRepository;
        this.userRepository = userRepository;
        this.skillRepository = skillRepository;
        this.careerRepository = careerRepository;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    public void run(String... args) throws Exception {
        System.out.println("Database initialization is starting...");

        long countPermissions = this.permissionRepository.count();
        long countRoles = this.roleRepository.count();
        long countUsers = this.userRepository.count();
        long countSkills = this.skillRepository.count();
        long countCareers = this.careerRepository.count();

        if(countPermissions == 0){
            ArrayList<Permission> permissions = new ArrayList<>();

            permissions.add(new Permission("Create recruiter", "/api/v1/recruiters", "POST", "RECRUITERS"));
            permissions.add(new Permission("Update recruiter", "/api/v1/recruiters", "PUT", "RECRUITERS"));
            permissions.add(new Permission("Delete recruiter", "/api/v1/recruiters/{id}", "DELETE", "RECRUITERS"));
            permissions.add(new Permission("Get recruiter", "/api/v1/recruiters/{id}", "GET", "RECRUITERS"));
            permissions.add(new Permission("Get all recruiters", "/api/v1/recruiters", "GET", "RECRUITERS"));

            permissions.add(new Permission("Create applicant", "/api/v1/applicants", "POST", "APPLICANTS"));
            permissions.add(new Permission("Update applicant", "/api/v1/applicants", "PUT", "APPLICANTS"));
            permissions.add(new Permission("Delete applicant", "/api/v1/applicants/{id}", "DELETE", "APPLICANTS"));
            permissions.add(new Permission("Get applicant", "/api/v1/applicants/{id}", "GET", "APPLICANTS"));
            permissions.add(new Permission("Get all applicants", "/api/v1/applicants", "GET", "APPLICANTS"));

            permissions.add(new Permission("Get all users", "/api/v1/users", "GET", "USERS"));
            permissions.add(new Permission("Update password", "/api/v1/users/update-password", "PUT", "USERS"));


            permissions.add(new Permission("Create career", "/api/v1/careers", "POST", "CAREERS"));
            permissions.add(new Permission("Update career", "/api/v1/careers", "PUT", "CAREERS"));
            permissions.add(new Permission("Delete career", "/api/v1/careers/{id}", "DELETE", "CAREERS"));
            permissions.add(new Permission("Get career", "/api/v1/careers/{id}", "GET", "CAREERS"));
            permissions.add(new Permission("Get all careers", "/api/v1/careers", "GET", "CAREERS"));

            permissions.add(new Permission("Create job", "/api/v1/jobs", "POST", "JOBS"));
            permissions.add(new Permission("Update job", "/api/v1/jobs", "PUT", "JOBS"));
            permissions.add(new Permission("Delete job", "/api/v1/jobs/{id}", "DELETE", "JOBS"));
            permissions.add(new Permission("Get job", "/api/v1/jobs/{id}", "GET", "JOBS"));
            permissions.add(new Permission("Get all jobs", "/api/v1/jobs", "GET", "JOBS"));

            permissions.add(new Permission("Create skill", "/api/v1/skills", "POST", "SKILLS"));
            permissions.add(new Permission("Update skill", "/api/v1/skills", "PUT", "SKILLS"));
            permissions.add(new Permission("Delete skill", "/api/v1/skills/{id}", "DELETE", "SKILLS"));
            permissions.add(new Permission("Get skill", "/api/v1/skills/{id}", "GET", "SKILLS"));
            permissions.add(new Permission("Get all skills", "/api/v1/skills", "GET", "SKILLS"));

            permissions.add(new Permission("Upload file", "/api/v1/files", "POST", "FILES"));
            permissions.add(new Permission("Download file", "/api/v1/files", "GET", "FILES"));

            permissions.add(new Permission("Create application", "/api/v1/applications", "POST", "APPLICATIONS"));
            permissions.add(new Permission("Update application", "/api/v1/applications", "PUT", "APPLICATIONS"));
            permissions.add(new Permission("Delete application", "/api/v1/applications/{id}", "DELETE", "APPLICATIONS"));
            permissions.add(new Permission("Get application", "/api/v1/applications/{id}", "GET", "APPLICATIONS"));
            permissions.add(new Permission("Get all applications by recruiter", "/api/v1/applications", "GET", "APPLICATIONS"));
            permissions.add(new Permission("Get all applications by applicant", "/api/v1/applications/by-applicant", "GET", "APPLICATIONS"));
            permissions.add(new Permission("Get all applications", "/api/v1/all-applications", "GET", "APPLICATIONS"));

            permissions.add(new Permission("Create permission", "/api/v1/permissions", "POST", "PERMISSIONS"));
            permissions.add(new Permission("Update permission", "/api/v1/permissions", "PUT", "PERMISSIONS"));
            permissions.add(new Permission("Delete permission", "/api/v1/permissions/{id}", "DELETE", "PERMISSIONS"));
            permissions.add(new Permission("Get permission", "/api/v1/permissions/{id}", "GET", "PERMISSIONS"));
            permissions.add(new Permission("Get all permissions", "/api/v1/permissions", "GET", "PERMISSIONS"));

            permissions.add(new Permission("Create role", "/api/v1/roles", "POST", "ROLES"));
            permissions.add(new Permission("Update role", "/api/v1/roles", "PUT", "ROLES"));
            permissions.add(new Permission("Delete role", "/api/v1/roles/{id}", "DELETE", "ROLES"));
            permissions.add(new Permission("Get role", "/api/v1/roles/{id}", "GET", "ROLES"));
            permissions.add(new Permission("Get all roles", "/api/v1/roles", "GET", "ROLES"));

            permissions.add(new Permission("Create a subscriber", "/api/v1/subscribers", "POST", "SUBSCRIBERS"));
            permissions.add(new Permission("Update a subscriber", "/api/v1/subscribers", "PUT", "SUBSCRIBERS"));
            permissions.add(new Permission("Delete a subscriber", "/api/v1/subscribers/{id}", "DELETE", "SUBSCRIBERS"));
            permissions.add(new Permission("Get a subscriber by id", "/api/v1/subscribers/{id}", "GET", "SUBSCRIBERS"));
            permissions.add(new Permission("Get subscribers with pagination", "/api/v1/subscribers", "GET", "SUBSCRIBERS"));

            permissions.add(new Permission("Create a blog", "/api/v1/blogs", "POST", "BLOGS"));
            permissions.add(new Permission("Update a blog", "/api/v1/blogs", "PUT", "BLOGS"));
            permissions.add(new Permission("Delete a blog", "/api/v1/blogs/{id}", "DELETE", "BLOGS"));
            permissions.add(new Permission("Get a blog by id", "/api/v1/blogs/{id}", "GET", "BLOGS"));
            permissions.add(new Permission("Get blogs with pagination", "/api/v1/blogs", "GET", "BLOGS"));

            this.permissionRepository.saveAll(permissions);
        }

        if(countRoles == 0){
            List<Permission> permissions = this.permissionRepository.findAll();

            Role role = new Role();
            role.setName("SUPER_ADMIN");
            role.setDescription("Admin will gain full permissions");
            role.setActive(true);
            role.setPermissions(permissions);

            this.roleRepository.save(role);
        }

        if(countUsers == 0){
            Role role = this.roleRepository.findByName("SUPER_ADMIN");

            User user = new Recruiter();
            user.setAddress("137/20 Phước Long, Nha Trang, Khánh Hòa");
            user.setContact(new Contact("admin@gmail.com", "0987654321"));
            user.setDob(LocalDate.of(2003, 12, 13));
            user.setFullName("Admin");
            user.setGender(Gender.MALE);
            user.setUsername("admin");
            user.setPassword(this.passwordEncoder.encode("12345678"));
            user.setRole(role);
            user.setEnabled(true);

            this.userRepository.save(user);
        }

        if(countSkills == 0){
            ArrayList<Skill> skills = new ArrayList<>();

            skills.add(new Skill("3ds Max"));
            skills.add(new Skill("ABAP"));
            skills.add(new Skill("Adobe"));
            skills.add(new Skill("Adobe Photoshop"));
            skills.add(new Skill("Adobe XD"));
            skills.add(new Skill("Agile"));
            skills.add(new Skill("AI"));
            skills.add(new Skill("Android"));
            skills.add(new Skill("Android studio"));
            skills.add(new Skill("Angular"));
            skills.add(new Skill("AngularJS"));
            skills.add(new Skill("Ansible"));
            skills.add(new Skill("Anti-malware"));
            skills.add(new Skill("Antivirus"));
            skills.add(new Skill("Apache Airflow"));
            skills.add(new Skill("Apache HttpClient"));
            skills.add(new Skill("Apache Spark"));
            skills.add(new Skill("API"));
            skills.add(new Skill("Appium"));
            skills.add(new Skill("Application Security"));
            skills.add(new Skill("ASP.NET"));
            skills.add(new Skill("Automation Test"));
            skills.add(new Skill("AUTOSAR"));
            skills.add(new Skill("AVR"));
            skills.add(new Skill("AWS"));
            skills.add(new Skill("AWS CloudFormation"));
            skills.add(new Skill("AWS Lambda"));
            skills.add(new Skill("Axure"));
            skills.add(new Skill("Azure"));
            skills.add(new Skill("Bash Shell"));
            skills.add(new Skill("Big Data"));
            skills.add(new Skill("Black box testing"));
            skills.add(new Skill("Blazor"));
            skills.add(new Skill("BLE"));
            skills.add(new Skill("Blender"));
            skills.add(new Skill("Blockchain"));
            skills.add(new Skill("Bootstrap"));
            skills.add(new Skill("BPMN"));
            skills.add(new Skill("Bridge Engineer"));
            skills.add(new Skill("BrowserStack"));
            skills.add(new Skill("Burp Suite"));
            skills.add(new Skill("Business Analysis"));
            skills.add(new Skill("Business Intelligence"));
            skills.add(new Skill("C#"));
            skills.add(new Skill("C++"));
            skills.add(new Skill("Change Management"));
            skills.add(new Skill("Chinese"));
            skills.add(new Skill("CI/CD"));
            skills.add(new Skill("Cisco"));
            skills.add(new Skill("C language"));
            skills.add(new Skill("Clean Architecture"));
            skills.add(new Skill("Cloud"));
            skills.add(new Skill("Cloud-native Architecture"));
            skills.add(new Skill("Cloud Security"));
            skills.add(new Skill("CompTIA Security+"));
            skills.add(new Skill("Computer Vision"));
            skills.add(new Skill("CRM"));
            skills.add(new Skill("CSS"));
            skills.add(new Skill("CSS 3"));
            skills.add(new Skill("Cucumber"));
            skills.add(new Skill("Cybersecurity"));
            skills.add(new Skill("Cypress"));
            skills.add(new Skill("Dart"));
            skills.add(new Skill("Data Analysis"));
            skills.add(new Skill("Database"));
            skills.add(new Skill("Databricks"));
            skills.add(new Skill("Data cleaning"));
            skills.add(new Skill("Data-driven"));
            skills.add(new Skill("Data Engineer"));
            skills.add(new Skill("Data mining"));
            skills.add(new Skill("Data modeling"));
            skills.add(new Skill("Data Quality Tools"));
            skills.add(new Skill("Data Science"));
            skills.add(new Skill("Data Warehousing"));
            skills.add(new Skill("DBA"));
            skills.add(new Skill("Deep Learning"));
            skills.add(new Skill("Design"));
            skills.add(new Skill("Design Systems"));
            skills.add(new Skill("DevOps"));
            skills.add(new Skill("DevSecOps"));
            skills.add(new Skill("Digital Forensics"));
            skills.add(new Skill("Django"));
            skills.add(new Skill("Docker"));
            skills.add(new Skill("Domain-Driven Design"));
            skills.add(new Skill("Ec-cube"));
            skills.add(new Skill("Elasticsearch"));
            skills.add(new Skill("Elixir"));
            skills.add(new Skill("ELK Stack"));
            skills.add(new Skill("ELT"));
            skills.add(new Skill("Embedded"));
            skills.add(new Skill("Embedded C"));
            skills.add(new Skill("English"));
            skills.add(new Skill("Enterprise Architecture"));
            skills.add(new Skill("Entity Framework"));
            skills.add(new Skill("ERP"));
            skills.add(new Skill("Ethers.js"));
            skills.add(new Skill("ETL"));
            skills.add(new Skill("Exploit Development"));
            skills.add(new Skill("Express"));
            skills.add(new Skill("ExpressJS"));
            skills.add(new Skill("F#"));
            skills.add(new Skill("FastAPI"));
            skills.add(new Skill("Figma"));
            skills.add(new Skill("Fiori"));
            skills.add(new Skill("Firebase"));
            skills.add(new Skill("Firewall"));
            skills.add(new Skill("Flask"));
            skills.add(new Skill("Flutter"));
            skills.add(new Skill("Fullstack"));
            skills.add(new Skill("Functional specifications"));
            skills.add(new Skill("Games"));
            skills.add(new Skill("GCP"));
            skills.add(new Skill("Generative AI"));
            skills.add(new Skill("Gin"));
            skills.add(new Skill("Git"));
            skills.add(new Skill("GitHub"));
            skills.add(new Skill("GitHub Actions"));
            skills.add(new Skill("GitLab"));
            skills.add(new Skill("Golang"));
            skills.add(new Skill("Google Cloud"));
            skills.add(new Skill("Governance, Risk & Compliance"));
            skills.add(new Skill("Grafana"));
            skills.add(new Skill("GraphQL"));
            skills.add(new Skill("Groovy"));
            skills.add(new Skill("Hadoop"));
            skills.add(new Skill("Hardware Troubleshooting"));
            skills.add(new Skill("Helm"));
            skills.add(new Skill("Hibernate"));
            skills.add(new Skill("HPE LoadRunner"));
            skills.add(new Skill("HTML"));
            skills.add(new Skill("HTML5"));
            skills.add(new Skill("Hugging Face Transformers"));
            skills.add(new Skill("Illustrator"));
            skills.add(new Skill("Information Security"));
            skills.add(new Skill("Integration test"));
            skills.add(new Skill("Interaction Design"));
            skills.add(new Skill("iOS"));
            skills.add(new Skill("IoT"));
            skills.add(new Skill("ISO 27001"));
            skills.add(new Skill("IT Audit"));
            skills.add(new Skill("IT Communication/Translation"));
            skills.add(new Skill("IT Governance"));
            skills.add(new Skill("ITIL Foundation"));
            skills.add(new Skill("IT Support"));
            skills.add(new Skill("J2EE"));
            skills.add(new Skill("Japanese"));
            skills.add(new Skill("Japanese IT Communication"));
            skills.add(new Skill("Java"));
            skills.add(new Skill("JavaScript"));
            skills.add(new Skill("Jenkins"));
            skills.add(new Skill("Jest"));
            skills.add(new Skill("Jira"));
            skills.add(new Skill("Jmeter"));
            skills.add(new Skill("JQuery"));
            skills.add(new Skill("JSON"));
            skills.add(new Skill("Juniper"));
            skills.add(new Skill("JUnit"));
            skills.add(new Skill("Kafka"));
            skills.add(new Skill("Katalon"));
            skills.add(new Skill("Koa"));
            skills.add(new Skill("Korean"));
            skills.add(new Skill("Kotlin"));
            skills.add(new Skill("Kubernetes"));
            skills.add(new Skill("Laravel"));
            skills.add(new Skill("Leadership"));
            skills.add(new Skill("LINQ"));
            skills.add(new Skill("Linux"));
            skills.add(new Skill("Live2D"));
            skills.add(new Skill("LLM"));
            skills.add(new Skill("Lua"));
            skills.add(new Skill("Machine Learning"));
            skills.add(new Skill("Magento"));
            skills.add(new Skill("Market research"));
            skills.add(new Skill("Maven"));
            skills.add(new Skill("Maya"));
            skills.add(new Skill("MFA"));
            skills.add(new Skill("MFC"));
            skills.add(new Skill("Microservices"));
            skills.add(new Skill("Microservices Architecture"));
            skills.add(new Skill("Microsoft Azure SQL Database"));
            skills.add(new Skill("Microsoft Dynamics 365"));
            skills.add(new Skill("Microsoft Power Apps"));
            skills.add(new Skill("Microsoft SQL Server"));
            skills.add(new Skill("MLOps"));
            skills.add(new Skill("Mobile Apps"));
            skills.add(new Skill("MongoDB"));
            skills.add(new Skill("Motion Design"));
            skills.add(new Skill("MVC"));
            skills.add(new Skill("MVP"));
            skills.add(new Skill("MVVM"));
            skills.add(new Skill("MySQL"));
            skills.add(new Skill("Neo4j"));
            skills.add(new Skill("NestJS"));
            skills.add(new Skill(".NET"));
            skills.add(new Skill(".Net Core"));
            skills.add(new Skill("Networking"));
            skills.add(new Skill("NextJS"));
            skills.add(new Skill("NLP"));
            skills.add(new Skill("Nmap"));
            skills.add(new Skill("NodeJS"));
            skills.add(new Skill("NoSQL"));
            skills.add(new Skill("NumPy"));
            skills.add(new Skill("Nuxt.js"));
            skills.add(new Skill("Objective C"));
            skills.add(new Skill("OCR"));
            skills.add(new Skill("Odoo"));
            skills.add(new Skill("OLTP"));
            skills.add(new Skill("OOP"));
            skills.add(new Skill("OpenCV"));
            skills.add(new Skill("OpenStack"));
            skills.add(new Skill("Oracle"));
            skills.add(new Skill("OutSystems"));
            skills.add(new Skill("Penetration Testing"));
            skills.add(new Skill("Pentest"));
            skills.add(new Skill("PHP"));
            skills.add(new Skill("Playwright"));
            skills.add(new Skill("PL/SQL"));
            skills.add(new Skill("PostgreSql"));
            skills.add(new Skill("Postman"));
            skills.add(new Skill("Power BI"));
            skills.add(new Skill("PowerShell"));
            skills.add(new Skill("PQA"));
            skills.add(new Skill("Presale"));
            skills.add(new Skill("Product Design"));
            skills.add(new Skill("Product Management"));
            skills.add(new Skill("Product Metrics"));
            skills.add(new Skill("Product Owner"));
            skills.add(new Skill("Product roadmap"));
            skills.add(new Skill("Product strategy"));
            skills.add(new Skill("Project Management"));
            skills.add(new Skill("Prometheus"));
            skills.add(new Skill("Prompt Engineering"));
            skills.add(new Skill("Prototyping"));
            skills.add(new Skill("Python"));
            skills.add(new Skill("PyTorch"));
            skills.add(new Skill("QA QC"));
            skills.add(new Skill("R"));
            skills.add(new Skill("Razor"));
            skills.add(new Skill("ReactJS"));
            skills.add(new Skill("React Native"));
            skills.add(new Skill("Redis"));
            skills.add(new Skill("Redux"));
            skills.add(new Skill("REST Assured"));
            skills.add(new Skill("Retrofit"));
            skills.add(new Skill("Risk Management"));
            skills.add(new Skill("Robot Framework"));
            skills.add(new Skill("ROS"));
            skills.add(new Skill("Ruby"));
            skills.add(new Skill("Ruby on Rails"));
            skills.add(new Skill("Rust"));
            skills.add(new Skill("RxJS"));
            skills.add(new Skill("Salesforce"));
            skills.add(new Skill("SAP"));
            skills.add(new Skill("Sass"));
            skills.add(new Skill("Scala"));
            skills.add(new Skill("Scrum"));
            skills.add(new Skill("SCSS"));
            skills.add(new Skill("Security"));
            skills.add(new Skill("Security Awareness Training"));
            skills.add(new Skill("Selenium"));
            skills.add(new Skill("Sharepoint"));
            skills.add(new Skill("Shopify"));
            skills.add(new Skill("SIEM"));
            skills.add(new Skill("Sketch"));
            skills.add(new Skill("SOAP"));
            skills.add(new Skill("SOAR"));
            skills.add(new Skill("Software Architecture"));
            skills.add(new Skill("SOLID Principles"));
            skills.add(new Skill("Solution Architecture"));
            skills.add(new Skill("Spark"));
            skills.add(new Skill("Splunk"));
            skills.add(new Skill("Spring"));
            skills.add(new Skill("Spring Boot"));
            skills.add(new Skill("SQL"));
            skills.add(new Skill("SQLite"));
            skills.add(new Skill("SRS"));
            skills.add(new Skill("Stakeholder management"));
            skills.add(new Skill("Statistical Analysis"));
            skills.add(new Skill("Strategy planning"));
            skills.add(new Skill("Swift"));
            skills.add(new Skill("Symfony"));
            skills.add(new Skill("System Admin"));
            skills.add(new Skill("System Architecture"));
            skills.add(new Skill("Tableau"));
            skills.add(new Skill("Tailwind"));
            skills.add(new Skill("Team Management"));
            skills.add(new Skill("TensorFlow"));
            skills.add(new Skill("Terraform"));
            skills.add(new Skill("TestComplete"));
            skills.add(new Skill("Tester"));
            skills.add(new Skill("TestNG"));
            skills.add(new Skill("Trello"));
            skills.add(new Skill("T-SQL"));
            skills.add(new Skill("TypeScript"));
            skills.add(new Skill("Ui5"));
            skills.add(new Skill("UI-UX"));
            skills.add(new Skill("UML"));
            skills.add(new Skill("Unit test"));
            skills.add(new Skill("Unity"));
            skills.add(new Skill("Unix"));
            skills.add(new Skill("Unreal Engine"));
            skills.add(new Skill("Usability testing"));
            skills.add(new Skill("User diagram"));
            skills.add(new Skill("User flows"));
            skills.add(new Skill("VBA"));
            skills.add(new Skill("vb.net"));
            skills.add(new Skill("Visual Basic"));
            skills.add(new Skill("Visual Design"));
            skills.add(new Skill("VMware"));
            skills.add(new Skill("VueJS"));
            skills.add(new Skill("Vuex"));
            skills.add(new Skill("Waterfall Methodology"));
            skills.add(new Skill("Web3.js"));
            skills.add(new Skill("Web API"));
            skills.add(new Skill("Web Application Firewall"));
            skills.add(new Skill("White box testing"));
            skills.add(new Skill("Windows"));
            skills.add(new Skill("Windows PowerShell"));
            skills.add(new Skill("Windows Server"));
            skills.add(new Skill("WinForms"));
            skills.add(new Skill("Wireframing"));
            skills.add(new Skill("Wordpress"));
            skills.add(new Skill("WPF"));
            skills.add(new Skill("XML"));
            skills.add(new Skill("Zend"));
            skills.add(new Skill("Lập kế hoạch bán hàng"));
            skills.add(new Skill("Đàm phán"));
            skills.add(new Skill("Phát triển kinh doanh"));
            skills.add(new Skill("Tạo khách hàng tiềm năng"));
            skills.add(new Skill("Tiếp thị kỹ thuật số"));
            skills.add(new Skill("Tiếp thị nội dung"));
            skills.add(new Skill("Quảng cáo Google"));
            skills.add(new Skill("Quảng cáo Facebook"));
            skills.add(new Skill("Tối ưu hóa công cụ tìm kiếm (SEO)"));
            skills.add(new Skill("Tiếp thị qua email"));
            skills.add(new Skill("Nghiên cứu thị trường"));
            skills.add(new Skill("Quản lý mạng xã hội"));
            skills.add(new Skill("Chăm sóc khách hàng"));
            skills.add(new Skill("Bán hàng qua điện thoại"));
            skills.add(new Skill("Quản lý tài khoản khách hàng"));
            skills.add(new Skill("Tiếp thị liên kết"));
            skills.add(new Skill("Lên kế hoạch bài giảng"));
            skills.add(new Skill("Thiết kế chương trình đào tạo"));
            skills.add(new Skill("Quản lý lớp học"));
            skills.add(new Skill("Công nghệ giáo dục"));
            skills.add(new Skill("Học trực tuyến"));
            skills.add(new Skill("Thiết kế bài kiểm tra"));
            skills.add(new Skill("Thuyết trình trước công chúng"));
            skills.add(new Skill("Cố vấn/Hướng dẫn"));
            skills.add(new Skill("Phát triển chương trình học"));
            skills.add(new Skill("Dạy học qua Zoom"));
            skills.add(new Skill("Google Classroom"));
            skills.add(new Skill("Hệ thống quản lý học tập (LMS)"));
            skills.add(new Skill("Quản lý khách sạn – nhà hàng"));
            skills.add(new Skill("Dịch vụ ăn uống (F&B)"));
            skills.add(new Skill("Tổ chức sự kiện"));
            skills.add(new Skill("Quản lý đặt chỗ"));
            skills.add(new Skill("Hệ thống POS"));
            skills.add(new Skill("Pha chế"));
            skills.add(new Skill("Dọn phòng khách sạn"));
            skills.add(new Skill("Hướng dẫn du lịch"));
            skills.add(new Skill("Giao tiếp đa ngôn ngữ"));
            skills.add(new Skill("Lễ tân khách sạn"));
            skills.add(new Skill("Phần mềm quản lý khách sạn"));
            skills.add(new Skill("AutoCAD"));
            skills.add(new Skill("Revit"));
            skills.add(new Skill("SolidWorks"));
            skills.add(new Skill("Thiết kế mô hình 3D"));
            skills.add(new Skill("Đọc bản vẽ kỹ thuật"));
            skills.add(new Skill("Kỹ thuật xây dựng dân dụng"));
            skills.add(new Skill("Dự toán công trình"));
            skills.add(new Skill("Thiết kế cơ khí"));
            skills.add(new Skill("Thiết kế hệ thống ống dẫn"));
            skills.add(new Skill("Đo đạc – Trắc địa"));
            skills.add(new Skill("Giám sát công trình"));
            skills.add(new Skill("Thiết kế hệ thống điện"));
            skills.add(new Skill("Phân tích kết cấu"));
            skills.add(new Skill("Tuân thủ tiêu chuẩn an toàn"));
            skills.add(new Skill("Chăm sóc điều dưỡng cơ bản"));
            skills.add(new Skill("Theo dõi dấu hiệu sinh tồn"));
            skills.add(new Skill("Sơ cứu"));
            skills.add(new Skill("Thuật ngữ y khoa"));
            skills.add(new Skill("Chăm sóc bệnh nhân"));
            skills.add(new Skill("Cấp phát thuốc"));
            skills.add(new Skill("Giáo dục sức khỏe"));
            skills.add(new Skill("Thủ thuật lâm sàng"));
            skills.add(new Skill("Hồ sơ y tế điện tử (EHR)"));
            skills.add(new Skill("Chứng nhận hồi sức tim phổi (CPR)"));
            skills.add(new Skill("Kiểm soát nhiễm khuẩn"));
            skills.add(new Skill("Chăm sóc người bệnh/già yếu"));

            this.skillRepository.saveAll(skills);
        }

        if(countCareers == 0){
            ArrayList<Career> careers = new ArrayList<>();

            careers.add(new Career("Công nghệ thông tin"));
            careers.add(new Career("Thiết kế đồ họa"));
            careers.add(new Career("Thiết kế UI/UX"));
            careers.add(new Career("Phát triển phần mềm"));
            careers.add(new Career("Khoa học dữ liệu"));
            careers.add(new Career("Trí tuệ nhân tạo"));
            careers.add(new Career("An ninh mạng"));
            careers.add(new Career("Quản trị mạng"));
            careers.add(new Career("Kỹ thuật phần cứng"));
            careers.add(new Career("Kỹ thuật điện – điện tử"));
            careers.add(new Career("Kỹ thuật cơ khí"));
            careers.add(new Career("Kỹ thuật xây dựng"));
            careers.add(new Career("Kiến trúc"));
            careers.add(new Career("Kinh doanh"));
            careers.add(new Career("Bán hàng"));
            careers.add(new Career("Marketing"));
            careers.add(new Career("Marketing kỹ thuật số"));
            careers.add(new Career("Tài chính"));
            careers.add(new Career("Kế toán"));
            careers.add(new Career("Kiểm toán"));
            careers.add(new Career("Ngân hàng"));
            careers.add(new Career("Nhân sự"));
            careers.add(new Career("Hành chính – văn phòng"));
            careers.add(new Career("Giáo dục – đào tạo"));
            careers.add(new Career("Biên – phiên dịch"));
            careers.add(new Career("Báo chí – Truyền thông"));
            careers.add(new Career("Luật – Pháp lý"));
            careers.add(new Career("Y tế – Điều dưỡng"));
            careers.add(new Career("Chăm sóc sức khỏe – Spa"));
            careers.add(new Career("Dược phẩm – Công nghệ sinh học"));
            careers.add(new Career("Nông – Lâm – Ngư nghiệp"));
            careers.add(new Career("Chế biến thực phẩm"));
            careers.add(new Career("Logistics – Chuỗi cung ứng"));
            careers.add(new Career("Xuất nhập khẩu"));
            careers.add(new Career("Vận tải – Lái xe"));
            careers.add(new Career("Hàng không"));
            careers.add(new Career("Hàng hải"));
            careers.add(new Career("Du lịch – Nhà hàng – Khách sạn"));
            careers.add(new Career("Tư vấn – Chăm sóc khách hàng"));
            careers.add(new Career("Thiết kế thời trang"));
            careers.add(new Career("Thủ công mỹ nghệ"));
            careers.add(new Career("Sản xuất – Vận hành – Bảo trì"));
            careers.add(new Career("Bảo vệ – An ninh"));
            careers.add(new Career("Bất động sản"));
            careers.add(new Career("Quản lý dự án"));
            careers.add(new Career("Thống kê – Phân tích dữ liệu"));
            careers.add(new Career("Thư viện – Lưu trữ"));
            careers.add(new Career("Môi trường – Tài nguyên"));
            careers.add(new Career("Thể thao – Giải trí"));
            careers.add(new Career("Mỹ thuật – Nhiếp ảnh – Điện ảnh"));
            careers.add(new Career("Tôn giáo – Xã hội – Tình nguyện"));
            careers.add(new Career("Game – Trò chơi điện tử"));
            careers.add(new Career("Bảo hiểm"));
            careers.add(new Career("Startup – Khởi nghiệp"));

            this.careerRepository.saveAll(careers);
        }

        if (countPermissions > 0 && countRoles > 0 && countUsers > 0 && countSkills > 0 && countCareers > 0) {
            System.out.println("Skip init database ~ Already have data...");
        } else {
            System.out.println("Database initialization ended...");
        }
    }
}
